version: 0.2
phases:
  build:
    commands:
       - mv .env .env.dev
       - mv .env.prod .env
       - npm install
       - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
