version: 0.2
phases:
  build:
    commands:
       - export REACT_APP_BACKEND=https://api-web.matrixscript.net
       - npm install
       - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
