version: 0.2
phases:
  build:
    commands:
       - mv .env .local.env
       - mv .prod.env .env
       - npm install
       - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
